"Install vim-plug if it doesn't exist
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

source $HOME/dotfiles/vim/config/variables.nvimrc

call plug#begin(data_dir . '/plugged')

source $HOME/dotfiles/vim/config/plugins/drawit.vim
source $HOME/dotfiles/vim/config/plugins/coc.vim
source $HOME/dotfiles/vim/config/plugins/vim-terraform.vim
source $HOME/dotfiles/vim/config/plugins/vim-fugitive.vim
source $HOME/dotfiles/vim/config/plugins/vim-gitgutter.vim
source $HOME/dotfiles/vim/config/plugins/vim-commentary.vim
source $HOME/dotfiles/vim/config/plugins/vim-context-commentstring.vim
"
"--- Appearance ---
source $HOME/dotfiles/vim/config/plugins/vim-gruvbox8.vim
source $HOME/dotfiles/vim/config/plugins/vim-polyglot.vim
source $HOME/dotfiles/vim/config/plugins/lightline.vim
source $HOME/dotfiles/vim/config/plugins/lightline-bufferline.vim

"--- Zen mode --
source $HOME/dotfiles/vim/config/plugins/wiki.vim
source $HOME/dotfiles/vim/config/plugins/mkdx.vim
source $HOME/dotfiles/vim/config/plugins/goyo.vim
source $HOME/dotfiles/vim/config/plugins/limelight.vim

"--- Search tools ---
source $HOME/dotfiles/vim/config/plugins/fzf.vim

"--- Text edit ---
source $HOME/dotfiles/vim/config/plugins/vim-highlightedyank.vim
source $HOME/dotfiles/vim/config/plugins/vim-surround.vim
source $HOME/dotfiles/vim/config/plugins/vim-repeat.vim
" source $HOME/dotfiles/vim/config/plugins/auto-pairs.vim

"--- Miscellaneous
source $HOME/dotfiles/vim/config/plugins/vial.vim
source $HOME/dotfiles/vim/config/plugins/vial-http.vim
source $HOME/dotfiles/vim/config/plugins/vim-wildwildws.vim
source $HOME/dotfiles/vim/config/plugins/vim-tmux-navigator.vim
source $HOME/dotfiles/vim/config/plugins/tmux-complete.vim
source $HOME/dotfiles/vim/config/plugins/fern.vim

"--- Golang ---
"source $HOME/dotfiles/vim/config/plugins/vim-go.vim

call plug#end()

source $HOME/dotfiles/vim/config/settings.nvimrc
source $HOME/dotfiles/vim/config/commands.nvimrc

source $HOME/dotfiles/vim/config/mappings/insert.nvimrc
source $HOME/dotfiles/vim/config/mappings/visual.nvimrc
source $HOME/dotfiles/vim/config/mappings/normal.nvimrc
