#!/usr/bin/env sh

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_topmost               off
yabai -m config window_placement             second_child
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          1.5
yabai -m config window_border_radius         0

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

yabai -m config layout                       bsp
yabai -m config top_padding                  26
yabai -m config bottom_padding               1
yabai -m config left_padding                 1
yabai -m config right_padding                1
yabai -m config window_gap                   1

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Preview$" manage=off 
yabai -m rule --add app="^Tinkerwell$" manage=off 
yabai -m rule --add app="^TablePlus$" manage=off 
yabai -m rule --add app="^Steam$" manage=off 
yabai -m rule --add app="^PhpStorm$" manage=off 

echo "yabai okai"
