#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
#yabai -m config status_bar_text_font         "FiraCode:Bold:10.0"
#yabai -m config status_bar_icon_font         "FiraCode:Regular:10.0"
#yabai -m config status_bar_background_color  0xff000000
#yabai -m config status_bar_foreground_color  0xffa8a8a8
#yabai -m config status_bar_space_icon_strip  ">_" "<?" "SQL" "COM" "www" "IRC" 7 8 9 0
#yabai -m config status_bar_power_icon_strip
#yabai -m config status_bar_space_icon        #
#yabai -m config status_bar_clock_icon        #

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_topmost               on
yabai -m config window_placement             second_child
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_placement      interior
yabai -m config window_border_width          1
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   1

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Preview$" manage=off border=off

yabai -m rule --add app="^Slack$" space=^1
yabai -m rule --add app="^Mail$" space=^1
yabai -m rule --add app="^TablePlus$" space=^2
yabai -m rule --add app="^PhpStorm$" space=^3
yabai -m rule --add app="^Alacritty$" space=^4

yabai -m rule --add app="^Firefox$" space=^5
yabai -m rule --add app="^Discord$" space=^6
yabai -m rule --add app="^Spotify$" space=^6

echo "yabai configuration loaded.."
