#. /usr/local/etc/profile.d/z.sh
. `brew --prefix`/etc/profile.d/z.sh
source $HOME/Gits/zsh-git-prompt/zshrc.sh

source $HOME/dotfiles/zsh/env
source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/scripts.zsh

setopt sharehistory
setopt extendedhistory
setopt HIST_IGNORE_DUPS
setopt PROMPT_SUBST
setopt autocd

PROMPT=' %B%F{119}%1~ >_%f%b '
RPROMPT='$(git_super_status)'
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[green]%}"

#autoload -Uz vcs_info
#precmd_vcs_info() { vcs_info }
#precmd_functions+=( precmd_vcs_info )
#RPROMPT=\$vcs_info_msg_0_
#zstyle ':vcs_info:git:*' formats '%F{113}%b'
#zstyle ':vcs_info:*' enable git

DEFAULT_USER=whoami``

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# if [ -z "$TMUX" ]
# then
#   tmux attach -t stormis || mux start jrnl 
# fi

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

bindkey -s '^f' 'fe^M'

autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

bindkey "ç" fzf-cd-widget


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/stormis/Playground/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/stormis/Playground/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/stormis/Playground/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/stormis/Playground/google-cloud-sdk/completion.zsh.inc'; fi
