. `brew --prefix`/etc/profile.d/z.sh
source $HOME/Gits/zsh-git-prompt/zshrc.sh

source $HOME/dotfiles/zsh/env
source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/scripts.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

setopt sharehistory
setopt extendedhistory
setopt HIST_IGNORE_DUPS
setopt PROMPT_SUBST
setopt autocd

PROMPT=' %B%F{119}%1~ >_%f%b '
RPROMPT='$(git_super_status)'
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[green]%}"
DEFAULT_USER=whoami``

bindkey -s '^f' 'fe^M'

autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

bindkey "ç" fzf-cd-widget

#export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
#if [ -f '/Users/stormis/Playground/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/stormis/Playground/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
#if [ -f '/Users/stormis/Playground/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/stormis/Playground/google-cloud-sdk/completion.zsh.inc'; fi
