local function map(mode, lhs, rhs)
  vim.keymap.set(mode, lhs, rhs, { silent = true })
end

map("n", "<c-f>", "<cmd>lua require('fzf-lua').files()<CR>")
map("n", "<leader>f", "<cmd>lua require'fzf-lua'.live_grep({ cmd = 'rg --line-number --column --color=always' }) <CR>")

map("v", "J", ":m '>+1<CR>gv=gv")
map("v", "K", ":m '<-2<CR>gv=gv")
map("n", "<C-d>", "<C-d>zz")
map("n", "<C-u>", "<C-u>zz")
map("n", "n", "nzzzv")
map("n", "N", "Nzzzv")
map("x", "<leader>p", [["_dP]])


map('i', '<up>', '<nop>')
map('i', '<down>', '<nop>')
map('i', '<left>', '<nop>')
map('i', '<right>', '<nop>')
map('i', ';;', '<Esc>A;<Esc>')
map('i', ',,', '<Esc>A,<Esc>')

map('v', 'H', '^')
map('v', 'L', 'g_')
map('v', '<', '<gv')
map('v', '>', '>gv')
map('v', 'y', 'myy`y')
map('v', 'Y', 'myY`y')

map('n', '<leader><leader>d', ':bd<CR>')

map('n', '<Up>', ':resize +5<CR>')
map('n', '<Down>', ':resize -5<CR>')
map('n', '<Left>', ':vertical resize +5<CR>')
map('n', '<Right>', ':vertical resize -5<CR>')

map('n', '<Leader>q', ':q<CR>')
map('n', '<Leader>w', ':w<CR>')
map('n', '<Leader><esc>', ':noh<CR>')
map('n', '<TAB>', ':bnext<CR>')
map('n', '<S-TAB>', ':bprevious<CR>')
map('n', '<Leader>bd', ':bd<CR>')
map('n', 'Y', 'y$')
map('n', 'gf', ':edit <cfile><CR>')
map('n', '<space>', 'zz')
map('n', 'H', '^')
map('n', 'L', '$')
map('n', 'q:', ':q<CR>')
map('n', '\\', '<C-^>')

map('i', '<ScrollWheelUp>', '<nop>')
map('i', '<S-ScrollWheelUp>', '<nop>')
map('i', '<C-ScrollWheelUp>', '<nop>')
map('i', '<ScrollWheelDown>', '<nop>')
map('i', '<S-ScrollWheelDown>', '<nop>')
map('i', '<C-ScrollWheelDown>', '<nop>')
map('i', '<ScrollWheelLeft>', '<nop>')
map('i', '<S-ScrollWheelLeft>', '<nop>')
map('i', '<C-ScrollWheelLeft>', '<nop>')
map('i', '<ScrollWheelRight>', '<nop>')
map('i', '<S-ScrollWheelRight>', '<nop>')
map('i', '<C-ScrollWheelRight>', '<nop>')

map('n', '<ScrollWheelUp>', '<nop>')
map('n', '<S-ScrollWheelUp>', '<nop>')
map('n', '<C-ScrollWheelUp>', '<nop>')
map('n', '<ScrollWheelDown>', '<nop>')
map('n', '<S-ScrollWheelDown>', '<nop>')
map('n', '<C-ScrollWheelDown>', '<nop>')
map('n', '<ScrollWheelLeft>', '<nop>')
map('n', '<S-ScrollWheelLeft>', '<nop>')
map('n', '<C-ScrollWheelLeft>', '<nop>')
map('n', '<ScrollWheelRight>', '<nop>')
map('n', '<S-ScrollWheelRight>', '<nop>')
map('n', '<C-ScrollWheelRight>', '<nop>')

